/* This file is automatically generated.  Do not edit. */
#ifndef _KUXSE_FLASK_H_
#define _KUXSE_FLASK_H_

#define MAC_TYPE_UNDEF	0
#define MAC_TYPE_GEN	1
#define MAC_TYPE_LOW	2
#define MAC_TYPE_HIGH	3
#define MAC_TYPE_PUBLIC	4

#endif
